import { useEffect, useRef, useState } from 'react'
import { Reveal } from '../components/Primitives'

/* ------------------------------------------------------------------
   Eleven languages, said loudly.

   The reason this section is big and dark rather than another card grid:
   for most of the people Yaadein is for, the language IS the product.
   An 82-year-old in Thanjavur who is losing her memory is not going to
   practise her English to be understood by software, and a companion she
   has to translate for is a companion she stops talking to.

   So the proof is the sentence, not the claim. Every line below came out
   of Sarvam's own /translate endpoint — one English sentence in, ten
   Indian languages back — which is exactly the call the product makes at
   runtime when an English-reading child opens their mother's Hindi
   memoir. Listing "11 languages ✓" as a feature bullet would have been
   cheaper and would have proved nothing.
   ------------------------------------------------------------------ */

/* [code, how the language names itself, English name, the sentence].
   The sentence is Yaadein's most-asked opening question. Generated by
   Sarvam /translate from the English at the top; not hand-written, and not
   invented by a model that doesn't do Indian languages for a living. */
const SAID_IN: [code: string, native: string, english: string, line: string][] = [
  ['hi-IN', 'हिन्दी', 'Hindi', 'मुझे अपने बचपन के घर के बारे में बताइए।'],
  ['ta-IN', 'தமிழ்', 'Tamil', 'உங்கள் குழந்தைப் பருவ வீடு பற்றிச் சொல்லுங்கள்.'],
  ['te-IN', 'తెలుగు', 'Telugu', 'మీ చిన్ననాటి ఇల్లు గురించి చెప్పండి.'],
  ['bn-IN', 'বাংলা', 'Bengali', 'আপনার শৈশবের বাড়ি সম্পর্কে বলুন।'],
  ['mr-IN', 'मराठी', 'Marathi', 'तुमच्या बालपणीच्या घराबद्दल सांगा.'],
  ['kn-IN', 'ಕನ್ನಡ', 'Kannada', 'ನಿಮ್ಮ ಬಾಲ್ಯದ ಮನೆಯ ಬಗ್ಗೆ ತಿಳಿಸಿ.'],
  ['gu-IN', 'ગુજરાતી', 'Gujarati', 'તમારા બાળપણના ઘર વિશે મને જણાવો.'],
  ['ml-IN', 'മലയാളം', 'Malayalam', 'നിങ്ങളുടെ കുട്ടിക്കാല വീടിന്റെ കഥ പറയൂ.'],
  ['pa-IN', 'ਪੰਜਾਬੀ', 'Punjabi', 'ਮੈਨੂੰ ਆਪਣੇ ਬਚਪਨ ਦੇ ਘਰ ਬਾਰੇ ਦੱਸੋ।'],
  ['od-IN', 'ଓଡ଼ିଆ', 'Odia', 'ଆପଣଙ୍କ ବାଲ୍ୟକାଳୀନ ଘର ବିଷୟରେ କୁହନ୍ତୁ।'],
  ['en-IN', 'English', 'English', 'Tell me about your childhood home.'],
]

/* Which Sarvam model does what. Named explicitly because "built on Sarvam"
   is a logo and this is the actual dependency. */
const STACK = [
  {
    model: 'saaras:v3',
    job: 'hears them',
    detail:
      'Speech to text in codemix mode, because a Delhi grandmother says “humne train pakdi” and neither a Hindi model nor an English one survives that sentence alone.',
  },
  {
    model: 'sarvam-30b',
    job: 'thinks',
    detail:
      'Every ordinary turn. An Indian-language model rather than a translation layer — the difference between talking to someone and talking through an interpreter.',
  },
  {
    model: 'sarvam-105b',
    job: 'handles the delicate turns',
    detail:
      'Stalled recall, the living memoir, the session notes. The moments where getting the tone wrong would hurt someone.',
  },
  {
    model: 'bulbul:v3',
    job: 'speaks back',
    detail:
      'Voice simran, slowed to 0.85 — the default pace is too quick to follow if your memory is failing, so we made her speak more slowly on purpose.',
  },
]

export function Languages() {
  return (
    <section id="languages" className="bg-tx relative overflow-hidden text-white">
      {/* a wash so the band isn't a flat black rectangle */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 top-0 h-[520px] opacity-[0.22]"
        style={{
          background:
            'radial-gradient(90% 60% at 50% 0%, #6d5cf0 0%, rgba(109,92,240,0) 70%)',
        }}
      />

      <div className="relative mx-auto w-full max-w-[1180px] px-5 py-24 sm:px-8 sm:py-32">
        <Reveal className="mx-auto max-w-4xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/5 px-3.5 py-1.5 font-mono text-[10px] tracking-[0.16em] text-white/70 uppercase backdrop-blur">
            <span className="bg-sr-green-600 live-dot h-1.5 w-1.5 rounded-full" />
            Powered end to end by Sarvam
          </span>

          {/* The number, at the size the number deserves. */}
          <p className="font-season mt-8 text-[128px] leading-[0.82] tracking-[-0.03em] sm:text-[200px]">
            11
          </p>
          <h2 className="font-season mt-3 text-[34px] leading-[1.06] tracking-[-0.02em] text-balance sm:text-[56px]">
            languages. Not translated —{' '}
            <em className="text-sr-indigo-300 not-italic">spoken.</em>
          </h2>

          <p className="mx-auto mt-7 max-w-2xl text-[16.5px] leading-relaxed text-pretty text-white/60 sm:text-[18px]">
            An 82-year-old in Thanjavur is not going to practise her English so
            software can understand her. Every sentence below is Yaadein&apos;s
            most-asked question, put through{' '}
            <span className="text-white">Sarvam&apos;s own translate endpoint</span> —
            the same call the product makes when an English-reading child opens
            their mother&apos;s Hindi memoir.
          </p>
        </Reveal>

        <Marquee />

        {/* The wall gets ONE Reveal, not one per cell.
            Twelve of them, each with its own IntersectionObserver and a
            staggered delay, left the bottom six stuck at opacity-0 — an
            observer that never fires never reveals, and a language wall with
            half the languages missing is worse than no animation at all. The
            stagger was decoration; being visible is the entire point. */}
        <Reveal className="mt-4 grid gap-px overflow-hidden rounded-[24px] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">
          {SAID_IN.map(([code, native, english, line]) => (
            <div key={code} className="bg-tx flex flex-col gap-3 px-6 py-7">
              <div className="flex items-baseline justify-between gap-3">
                {/* lang= so a screen reader switches voice. Without it every
                    line below is read with an English voice, which on a page
                    whose whole claim is "spoken, not translated" is the one
                    accessibility miss that is also a credibility miss. */}
                <span lang={code} className="font-season text-[27px] leading-none text-white">
                  {native}
                </span>
                <span className="shrink-0 font-mono text-[9.5px] tracking-[0.14em] text-white/35 uppercase">
                  {native === english ? code : english}
                </span>
              </div>
              <p lang={code} className="text-[16px] leading-relaxed text-pretty text-white/80">
                {line}
              </p>
            </div>
          ))}

          {/* an honest twelfth cell rather than a dead gap in the grid */}
          <div className="bg-tx flex flex-col justify-center px-6 py-7">
            <p className="font-mono text-[9.5px] tracking-[0.14em] text-white/35 uppercase">
              and the one that matters most
            </p>
            <p className="font-season mt-2 text-[21px] leading-snug text-balance text-white/90">
              Whichever two she mixes mid-sentence.
            </p>
            <p className="mt-2 text-[13px] leading-relaxed text-pretty text-white/50">
              Codemix speech-to-text, so “humne train pakdi thi” is one thought,
              not two failed transcriptions.
            </p>
          </div>
        </Reveal>

        {/* the models, named */}
        <Reveal delay={120} className="mt-16">
          <p className="text-center font-mono text-[10px] tracking-[0.18em] text-white/40 uppercase">
            Every model in the product is Sarvam&apos;s
          </p>
          <div className="mt-7 grid gap-px overflow-hidden rounded-[20px] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">
            {STACK.map((s) => (
              <div key={s.model} className="bg-tx px-5 py-6">
                <p className="font-mono text-[12.5px] text-sr-indigo-300">{s.model}</p>
                <p className="mt-2 text-[14.5px] font-medium text-white">{s.job}</p>
                <p className="mt-2 text-[12.5px] leading-relaxed text-pretty text-white/50">
                  {s.detail}
                </p>
              </div>
            ))}
          </div>
        </Reveal>

        <Reveal delay={180}>
          <p className="mx-auto mt-12 max-w-2xl text-center text-[14px] leading-relaxed text-pretty text-white/45">
            No OpenAI. No Gemini. No translation shim in front of an English
            model.{' '}
            <span className="text-white/80">
              Nothing in Yaadein does language work except Sarvam.
            </span>
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-2.5">
            <a href="#/try" className="pill bg-white text-tx hover:bg-sr-indigo-100">
              Hear it in your language
            </a>
            <a
              href="#/waitlist"
              className="pill border border-white/20 bg-transparent text-white hover:border-white/60"
            >
              Claim a free seat
            </a>
          </div>
        </Reveal>
      </div>
    </section>
  )
}

/* ── the scrolling band ───────────────────────────────────────────── */

/* Native scripts at speed. The point is peripheral: you should register
   "that is a lot of different writing systems" before you read a word of it.
   Duplicated twice and translated -50% so the loop has no visible seam, and
   paused for anyone who asked their OS to stop moving things. */
function Marquee() {
  const [reduced, setReduced] = useState(false)
  const seen = useRef(false)

  useEffect(() => {
    const q = window.matchMedia('(prefers-reduced-motion: reduce)')
    setReduced(q.matches)
    const on = () => setReduced(q.matches)
    q.addEventListener('change', on)
    return () => q.removeEventListener('change', on)
  }, [])

  /* one pass, so it doesn't re-trigger its own reveal on scroll */
  if (!seen.current) seen.current = true

  const row = (
    <>
      {SAID_IN.map(([code, native]) => (
        <span key={code} className="flex items-center gap-7 px-7">
          <span lang={code} className="font-season text-[38px] leading-none whitespace-nowrap text-white/85 sm:text-[52px]">
            {native}
          </span>
          <span aria-hidden className="text-sr-indigo-300/60 text-[20px]">
            ·
          </span>
        </span>
      ))}
    </>
  )

  return (
    <div
      aria-hidden
      className="relative mt-14 -mx-5 overflow-hidden sm:-mx-8"
      style={{
        /* fade both edges into the band instead of clipping mid-glyph */
        maskImage:
          'linear-gradient(to right, transparent, black 8%, black 92%, transparent)',
        WebkitMaskImage:
          'linear-gradient(to right, transparent, black 8%, black 92%, transparent)',
      }}
    >
      <div className={`flex w-max ${reduced ? '' : 'animate-ticker'}`}>
        <span className="flex">{row}</span>
        <span className="flex">{row}</span>
      </div>
    </div>
  )
}
